### ISSUE TITLE
Implementing the pages of the home page, login and register pages

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/team_Taiga-soen341project2022#10]
I and Michael will work on the home page of the website.  I will also work on the login and register page. 
The static page with CSS, will only be done. Also we will make sure the page is responsive to other devices.

**Comment by Iwuh** [comment]
This is good for sprint 2. If possible though, I think it would be ideal to have a barebones "Hello World" React project created during sprint 1 (#4) so that we can show our technologies used.

**Comment by imran1289-ah** [comment]
Cool, I will look into that

**Comment by imran1289-ah** [comment]
There are some missing inputs in the register page (as discussed in the api design meeting )

**Comment by MichaelDjabauri** [comment]
@imran1289-ah I'm closing this issue since the login, register, and home are done
