### ISSUE TITLE
Designing  pages of the list of products for each type

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/team_Taiga-soen341project2022#16]
Someone should design the list of items for each times of product we have 

![image](https://user-images.githubusercontent.com/77070862/151713296-a5933ddd-bcb2-42fe-9468-6c27703055a1.png)

For example, In amazon, this is the list of electronics, there are some apple accessories, some tv box, etc. 

We all have to do a list like this for each type of product we have. 

For example for electronics, there will be some computers, games, phones etc

We will have to do this for each type of products (electronics, books etc)

**Comment by Iwuh** [comment]
Why design static pages? We can have the frontend use the backend to fetch a list of products from the database and render it on the client side.

**Comment by imran1289-ah** [comment]
Yea, that's better
