### ISSUE TITLE
Implementing pages for each product 

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/team_Taiga-soen341project2022#17]
Someone should be responsible for designing the page where we get the details of a product

![image](https://user-images.githubusercontent.com/77070862/151713447-409dd212-a047-48e9-ab75-0ee3c8d6af3b.png)

For example, this is details for the amazon fire stick.

We will have to add the price and all the necessary details, no need to put too many details like in this example.

We will have to do this for each product we have in our store

**Comment by Iwuh** [comment]
Same as #16, we can store details for each product in a database and fetch them then render in the browser.

**Comment by imran1289-ah** [comment]
yea better idea

**Comment by imran1289-ah** [comment]
this task will no longer be done
