### ISSUE TITLE
Task: Other sprint 1 documents

### ISSUE THREAD

**Issue by Iwuh** [imran1289-ah/team_Taiga-soen341project2022#3]
According to the requirements on Moodle, we need to write our plan for the next sprint and the task breakdown for this sprint.
Edit: We also need to make sure that all the required details are in the README.

**Comment by imran1289-ah** [comment]
i added what i was gonna do for the next sprint #10. Do we need a document ? requirements says to create issues under the milestones for next sprint.

**Comment by Iwuh** [comment]
You're right, I think that was added to Moodle after I opened this issue. Issues are fine for next sprint's plan, we don't need a document.

**Comment by imran1289-ah** [comment]
I added some issues for next sprint
