### ISSUE TITLE
User Story#1: Login/register customer

### ISSUE THREAD

**Issue by zihao429** [imran1289-ah/team_Taiga-soen341project2022#34]
As a customer, I want to be able to create a new account and/or log in to an existing account because I want to be able to shop for products.

Tasks: 
- Design and implement login page form.
- Design and implement register page form and save account information.
- Design and implement a list of products page.
- Design and implement a homepage of the website.

Tasks References : #29 #16 #17 #10 #39 #22 #38 

Acceptance tests:

Positive case
1. The customer clicks ‘Login’ button.
2. Login form appears.
3. The customer enters correct information and clicks ‘Login’ button.
4.  The customer clicks on their desired category.
5. A list of available products related to the clicked category and their description is shown.

Negative case
1. The customer clicks ‘Login’ button.
2. Login form appears.
3. The customer enters incorrect information and clicks ‘Login’ button.
4. An error message is displayed.

**Comment by MichaelDjabauri** [comment]
User Story 1 is completed and all the tasks (#29 #16 #17 #10 #39 #22 #38) are finished
